# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: BuildDockerImage
      run: docker build . --file Dockerfile --tag docker:0.1
    - uses: actions/checkout@v1
    - name: docker build and push aliyun
      env:
        aliyun_username: ${{ secrets.DOCKER_USERNAME }}
        aliyun_password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login --username=${aliyun_username} registry.cn-hangzhou.aliyuncs.com --password=${aliyun_password}
        docker tag docker:0.1 registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1
        docker push registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1

  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop $(docker ps --filter ancestor=registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1 -q)
          docker rm -f $(docker ps --filter ancestor=registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1 -q)
          docker rmi -f $(docker images registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon -q)
          docker login --username=${{ secrets.DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
          docker pull registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1
          docker run -d -p 8000:8080 registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1