# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/checkout@v1
    - name: docker build and push aliyun
      env:
        aliyun_username: ${{ secrets.DOCKER_USERNAME }}
        aliyun_password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        sudo docker login --username=${aliyun_username} registry.cn-hangzhou.aliyuncs.com --password=${aliyun_password}
        sudo docker build . --file Dockerfile --tag docker:0.1
        sudo docker tag docker:0.1 registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1
        sudo docker push registry.cn-hangzhou.aliyuncs.com/mydockerpractice/adon:0.1

